language: elixir

elixir:
  - '1.13.1'

otp_release:
  - '24.1'

addons:
  postgresql: '14'
  apt:
    packages:
    - postgresql-14
    - postgresql-client-14

env:
  - MIX_ENV=test

services:
  - postgresql

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

script:
  - mix test

cache:
  directories:
    - _build
    - deps
