language: elixir

elixir:
  - '1.13.1'

otp_release:
  - '24.1'

# env:
#   - MIX_ENV=test

services:
  - postgresql

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

script:
  - MIX_ENV=test SECRET_KEY_BASE=test mix test

cache:
  directories:
    - _build
    - deps
