language: elixir

elixir:
  - '1.13.1'

otp_release:
  - '24.1'

addons:
  postgresql: '9.4'

services:
  - postgresql

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

script:
  - mix test
